[general]
import = [
    "../../themes/alacritty-theme/themes/catppuccin_latte.toml"
]

[font]
normal = { family = "UDEV Gothic NFLG", style = "Regular" }

# [colors.primary]
# background = "#FFFFFF"

[terminal]
osc52 = "CopyPaste"

