vim9script
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8,sjis,iso-2022-jp,euc-jp 
scriptencoding utf-8

set fileformats=unix,dos

if &compatible
    set nocompatible
endif

if exists('+termguicolors')
    set termguicolors
endif

# dpp settings

$BASE_DIR = "<sfile>" -> expand() -> fnamemodify(":h")
const dpp_base = "~/.cache/dpp" -> expand()

if !dpp_base -> isdirectory()
    call mkdir(dpp_base, "p")
endif

def PreloadPlugin(plugin: string)
    const dir = dpp_base .. "/repos/github.com/" .. plugin
    if !dir -> isdirectory()
        execute "!git clone https://github.com/" .. plugin dir
    endif
    execute "set runtimepath^=" .. dir
enddef

call PreloadPlugin("Shougo/dpp.vim")
if dpp_base->dpp#min#load_state()
    call PreloadPlugin("Shougo/dpp-ext-installer")
    call PreloadPlugin("Shougo/dpp-protocol-git")
    call PreloadPlugin("vim-denops/denops.vim")
    autocmd User DenopsReady
    : echohl WarningMsg
    | echomsg 'dpp load_state() is failed'
    | echohl NON
    | call dpp#make_state(dpp_base, "~/.config/vim/dpp.ts")
endif

# opts

set ambiwidth=single

set autoread
set clipboard^=unnamedplus

set number
set cursorline

set hlsearch
set incsearch
set ignorecase
set smartcase
set wrapscan
set whichwrap=b,s,h,l,<,>,[,],~

set smartindent
set autoindent
set expandtab
set tabstop=4
set shiftwidth=4

set laststatus=2
set wildmenu
set hidden

set updatetime=300
set noshowmode
set shortmess+=c

filetype plugin indent on
syntax on

var mapleader = " "
nnoremap j gj
nnoremap k gk
nnoremap <down> gj
nnoremap <up> gk

defcompile
